<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","right":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50"},"margin":{"top":"0","bottom":"0"}},"elements":{"link":{"color":{"text":"var:preset|color|base-2"}}}},"backgroundColor":"contrast","textColor":"base-2","layout":{"type":"constrained"}} --><html><body><div class="wp-block-group alignfull has-base-2-color has-contrast-background-color has-text-color has-background has-link-color" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)">
	<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|50","left":"var:preset|spacing|60"}}}} -->
	<div class="wp-block-columns alignwide">
		<!-- wp:column {"verticalAlignment":"stretch","width":"60%","style":{"spacing":{"padding":{"right":"0"}}}} -->
		<div class="wp-block-column is-vertically-aligned-stretch" style="padding-right:0;flex-basis:60%">
			<!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between","justifyContent":"stretch"}} -->
			<div class="wp-block-group" style="min-height:100%">
				<!-- wp:image {"aspectRatio":"9/16","scale":"cover","sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
				<figure class="wp-block-image size-large is-style-rounded">
					<img src="http://neics.org/wp-content/themes/twentytwentyfour/patterns/%3Cbr%20/%3E%0A%3Cb%3EFatal%20error%3C/b%3E:%20%20Uncaught%20Error:%20Call%20to%20undefined%20function%20esc_url()%20in%20/Users/dom/Local%20Sites/neicspresentations/app/public/wp-content/themes/twentytwentyfour/patterns/gallery-project-layout.php:20%0AStack%20trace:%0A#0%20%7Bmain%7D%0A%20%20thrown%20in%20%3Cb%3E/Users/dom/Local%20Sites/neicspresentations/app/public/wp-content/themes/twentytwentyfour/patterns/gallery-project-layout.php%3C/b%3E%20on%20line%20%3Cb%3E20%3C/b%3E%3Cbr%20/%3E%0A"></figure></div></div></div></div></body></html>
<!-- Powered by Staatic (https://staatic.com/) -->